language: node_js
node_js: "lts/*"
cache:
  directories:
    - "node_modules"

install:
  - npm install
  - npm test

script:
  - npm run build

deploy:
  provider: pages
  local-dir: build
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master